# Generated by Django 6.0.5 on 2026-05-28 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_forgotpasswordotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgotpasswordotp",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
