# Generated by Django 6.0.5 on 2026-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("news", "News Article"),
                    ("social", "Social Media Post"),
                    ("review", "User Review"),
                    ("blog", "Blog Content"),
                    ("forum", "Forum Discussion"),
                    ("other", "Other / General"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
